### ISSUE TITLE
[Question] How to get anomaly scores?

### ISSUE THREAD

**Issue by eigenvektorin** [bit-ml/date#2]
I am very interested in your model and am currently trying to replicate your results for the ag_news dataset. I finally managed to run `train_ag.py` which saves the pytorch model and the configs to the output_dir. Unfortunately, I can't figure out what the next steps are to get the anomaly scores. Can it be that a file is missing in which the evaluation is implemented?

**Comment by andreimano** [comment]
Hi @eigenvektorin ! Unfortunately, there's no "official" way of directly extracting the scores - we plan on doing a full refactorization of the code soon such that the models can be compatible and directly loaded using the huggingface library.

In the meanwhile, a way of extracting anomaly scores is by setting the `extract_scores` field from the `train_args` dictionary to `1`. This will extract the top 5 fp/fn/tp/tn texts to the `scores_export_path` path, you could edit the code to obtain your results for the whole dataset.

Another (maybe easier) way of exporting the probabilities is to go to [this line](https://github.com/bit-ml/date/blob/58693948b9ce2caf7b3c4a36c824f1b7b1a86bb2/simpletransformers/simpletransformers/language_modeling/language_modeling_model.py#L1555) and write `anomaly_scores_pl_electra_2` and `inlier_scores_pl_electra_2` somewhere on your disk.

Please note that we have two different lists of scores (inlier and outlier) because we make inference on the corresponding subsets sequentially. If you just want to feed some data to the model and extract the scores without benchmarking the model, it should be easy enough to do inference once and just dump the scores.

I hope this helps you, don't hesitate to contact us if you have any other inquiry :smile: !

**Comment by eigenvektorin** [comment]
Thank you very much!
